// Generated by https://quicktype.io

export interface SimpsonDetailsResponse {
    result: SimpsonDetails[];
}

export interface SimpsonDetails {
    _id: string;
    Nombre: string;
    Historia: string;
    Imagen: string;
    Genero: string;
    Estado: string;
    Ocupacion: string;
}
